# Development
# url: http://localhost:4000

# Production
url: http://tinyfactory.github.com/Tiny-Factory-Docs


permalink: :date
exclude: ['Rakefile', 'README.md', 'config.rb']
pygments: true

# configuration required for some pages

domain: http://tinyfactory.github.com
title: Tiny Factory Docs
author: Tiny Factory
email: hello@tinyfactory.co

google_analytics:
  account: UA-20145334-1

prose:
  rooturl: "_posts"