# Development
# url: http://localhost:4000

# Production
url: http://tinyfactory.github.com/Tiny-Factory-Docs


permalink: :date
exclude: ['Rakefile', 'README.md', 'config.rb']
pygments: true
markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

# configuration required for some pages

domain: http://tinyfactory.github.com
title: Tiny Factory Docs
author: Tiny Factory
email: hello@tinyfactory.co

# google_analytics:
#   account: UA-XXXXX-X

prose:
  rooturl: "_posts"