# Development
# url: http://localhost:4000
# baseurl: /

# Production
url: http://tinyfactory.github.com/Tiny-Factory-Docs/
# baseurl: /Tiny-Factory-Docs


permalink: :date
exclude: ['Rakefile', 'README.md', 'config.rb']
pygments: false

# configuration required for some pages

domain: http://tinyfactory.github.com
title: Tiny Factory Docs
author: Tiny Factory
email: hello@tinyfactory.co

# google_analytics:
#   account: UA-XXXXX-X

prose:
  rooturl: "_posts"