# standard jekyll configuration

# Development
# url: http://localhost:4000/

# Production
baseurl: /Tiny-Factory-Docs
url: http://tinyfactory.github.com/Tiny-Factory-Docs/

permalink: :date
exclude: ['Rakefile', 'README.md', 'config.rb']
pygments: true

# configuration required for some pages

domain: http://tinyfactory.github.com
title: Tiny Factory Docs
author: Tiny Factory
email: hello@tinyfactory.co

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

# github:
#   username: ghusername

# disqus:
#   id: disqusid

